In [2]:
import pandas as pd

In [2]:
office_data = pd.read_excel('../data/rental_office_(july_to_nov_2018).xlsx')
office_data.head()

    month  code            office  rentals  returns
0  201806   101  101. (구)합정동 주민센터      832      807
1  201806   102   102. 망원역 1번출구 앞     2819     2568
2  201806   103   103. 망원역 2번출구 앞     1977     1769
3  201806   104   104. 합정역 1번출구 앞     1682     1610
4  201806   105   105. 합정역 5번출구 앞     1105      925

In [3]:
location_data = pd.read_csv('../data/office_info_clean.csv')
location_data.head()

   Unnamed: 0  code   latitude   longitude install_date   LCD   QR type
0           1   301  37.575794  126.971451   2015-10-07  16.0  NaN  LCD
1           2   302  37.575947  126.974060   2015-10-07  12.0  NaN  LCD
2           3   303  37.571770  126.974663   2015-10-07   8.0  NaN  LCD
3           4   304  37.572113  126.977577   2021-01-26   NaN  7.0   QR
4           5   305  37.572582  126.978355   2015-10-07  16.0  NaN  LCD

In [13]:
location_data['location'] = list(zip(location_data.latitude, location_data.longitude))
location_data.head()

,Unnamed: 0,code,latitude,longitude,install_date,LCD,QR,type,location
0,1,301,37.575794,126.971451,2015-10-07,16.0,NaN,LCD,"(37.575794, 126.971451)"
1,2,302,37.575947,126.974060,2015-10-07,12.0,NaN,LCD,"(37.575947, 126.97406)"
2,3,303,37.571770,126.974663,2015-10-07,8.0,NaN,LCD,"(37.57177, 126.974663)"
3,4,304,37.572113,126.977577,2021-01-26,NaN,7.0,QR,"(37.572113, 126.977577)"
4,5,305,37.572582,126.978355,2015-10-07,16.0,NaN,LCD,"(37.572582, 126.978355)"

In [15]:
locationDict = dict(zip(location_data.code, location_data.location))
locationDict

{301: (37.57579422, 126.9714508),
 302: (37.57594681, 126.9740601),
 303: (37.57176971, 126.9746628),
 304: (37.57211304, 126.9775772),
 305: (37.57258224, 126.9783554),
 306: (37.57080841, 126.9764328),
 307: (37.56999969, 126.9710999),
 308: (37.56996918, 126.973938),
 309: (37.56988907, 126.9764557),
 314: (37.5797081, 126.9808579),
 316: (37.57039642, 126.9817886),
 326: (37.57624054, 126.9861603),
 327: (37.57335663, 126.9874649),
 328: (37.57039642, 126.9881897),
 329: (37.56834412, 126.9878922),
 334: (37.5705986, 126.9917908),
 335: (37.57019806, 126.9912567),
 337: (37.57897949, 126.9964752),
 338: (37.57095718, 126.9971237),
 339: (37.57106781, 126.9981918),
 340: (37.58562851, 127.000679),
 341: (37.58156967, 127.0017853),
 342: (37.57978439, 127.002533),
 343: (37.57543182, 127.004982),
 344: (37.57403564, 127.0067215),
 345: (37.57330704, 127.0007095),
 348: (37.57202911, 126.9607849),
 349: (37.57633209, 126.9685898),
 351: (37.58507919, 126.9706192),
 352: (37.58341599, 126.9852371),
 353: (37.57938766, 126.9849472),
 354: (37.57915497, 126.9889603),
 355: (37.57650757, 127.0024567),
 356: (37.57714462, 127.0020599),
 358: (37.58250046, 126.9985352),
 359: (37.57606125, 126.9976807),
 361: (37.57324219, 127.0159073),
 362: (37.57222366, 127.0227051),
 363: (37.57575989, 127.0228348),
 364: (37.57933426, 127.0150833),
 367: (37.57384872, 126.9586945),
 368: (37.5692482, 126.9805374),
 369: (37.57549286, 126.9785004),
 385: (37.56983566, 126.9826584),
 388: (37.58573532, 127.0016098),
 393: (37.57014084, 127.0093765),
 394: (37.56748962, 126.9659195),
 395: (37.56885529, 126.9645615),
 397: (37.57048035, 126.9966354),
 446: (37.60012817, 126.9578323),
 447: (37.60399246, 126.9619446),
 449: (37.60871887, 126.9728622),
 450: (37.58360291, 126.9725494),
 451: (37.58351517, 126.9796677),
 452: (37.57123947, 127.0044098),
 453: (37.57114029, 127.0006714),
 454: (37.57035828, 126.9863815),
 455: (37.570961, 127.0060577),
 456: (37.57447052, 127.0198288),
 457: (37.57131958, 127.0072098),
 458: (37.56993866, 126.9775391),
 461: (37.57436371, 126.9723663),
 462: (37.60351181, 126.9620667),
 464: (37.58419037, 126.9816971),
 465: (37.58760452, 126.9835968),
 486: (37.60627365, 126.9683228),
 3401: (37.57376099, 127.0139389),
 3402: (37.57660675, 127.0055695),
 3403: (37.5695076, 126.9670105),
 3404: (37.57185364, 127.0023575),
 3405: (37.57455063, 126.9705505),
 3406: (37.57405853, 126.9757996),
 3407: (37.57580566, 126.9833908),
 3408: (37.57051086, 126.9833679),
 3410: (37.5724678, 126.99189),
 3411: (37.5707016, 126.994812),
 3412: (37.5703125, 126.994545),
 3413: (37.57320023, 126.997963),
 3414: (37.57117462, 127.0022278),
 3415: (37.57146072, 127.010788),
 3416: (37.5715332, 127.0156174),
 3417: (37.57772446, 127.0152512),
 3418: (37.57998657, 127.0150604),
 3419: (37.58194733, 126.9973679),
 3420: (37.58327484, 126.9988556),
 3421: (37.58385468, 127.0018539),
 3422: (37.58479691, 126.9971314),
 3423: (37.57583618, 127.0006943),
 3425: (37.57529068, 126.968956),
 3426: (37.57501602, 126.9575501),
 3427: (37.57666779, 126.9558487),
 3428: (37.59512711, 126.9634934),
 3429: (37.59725952, 126.963089),
 3430: (37.60950089, 126.9566803),
 3431: (37.60760117, 126.9576874),
 3432: (37.56999207, 126.9883423),
 4702: (37.60604858, 126.9676361),
 4710: (37.58112335, 126.9709854),
 4711: (37.58983612, 126.9993439),
 300: (37.56805038, 126.9692307),
 310: (37.56887817, 126.9774704),
 311: (37.566612, 126.97747),
 312: (37.56467438, 126.976738),
 318: (37.56852722, 126.9825516),
 320: (37.56622314, 126.9835892),
 321: (37.56546402, 126.9841385),
 322: (37.56447601, 126.986969),
 324: (37.56134033, 126.9804001),
 331: (37.56638336, 126.9872055),
 332: (37.56599045, 126.987793),
 336: (37.56261826, 126.992836),
 346: (37.56918335, 127.0098801),
 347: (37.56533051, 127.007843),
 370: (37.56322861, 126.9748383),
 371: (37.55887222, 127.0055389),
 372: (37.55429459, 127.0112),
 373: (37.555859, 127.013855),
 374: (37.5604744, 127.0140762),
 375: (37.56371689, 127.018425),
 378: (37.56980515, 127.0169525),
 379: (37.55599976, 126.9733582),
 380: (37.56386566, 127.0027466),
 381: (37.55853271, 127.0069885),
 382: (37.55519867, 127.0100479),
 383: (37.5658493, 127.0164032),
 384: (37.55978012, 126.9685059),
 387: (37.56699371, 127.0034638),
 389: (37.5667305, 126.9966049),
 390: (37.56138992, 126.9953537),
 391: (37.56543732, 126.9733048),
 398: (37.56655884, 126.9924393),
 399: (37.55410767, 126.9654083),
 428: (37.56439972, 126.9914322),
 429: (37.54988861, 127.0073471),
 430: (37.56217194, 127.0062637),
 431: (37.57089996, 127.0195236),
 433: (37.56634521, 126.9822922),
 434: (37.56148911, 127.0239334),
 435: (37.55686188, 126.9756165),
 826: (37.55536652, 126.9686432),
 441: (37.55989075, 126.9714966),
 442: (37.55641556, 126.9691925),
 443: (37.5621109, 126.9707184),
 444: (37.557602, 126.97258),
 445: (37.56015396, 126.9741058),
 466: (37.56584167, 126.9798126),
 467: (37.5622139, 126.9808655),
 468: (37.56415939, 126.9794846),
 469: (37.5592308, 126.9801407),
 470: (37.55974579, 126.9800034),
 471: (37.56035995, 126.9826508),
 472: (37.56787109, 126.9889832),
 473: (37.56605148, 126.9979858),
 474: (37.56629944, 127.0084915),
 475: (37.56764984, 127.0118103),
 476: (37.56443024, 127.0099564),
 477: (37.55928802, 127.0026856),
 479: (37.55937576, 127.0060272),
 480: (37.55432129, 127.010704),
 481: (37.56703186, 127.0157929),
 482: (37.55994034, 127.0184784),
 483: (37.54758453, 127.0064392),
 484: (37.55614853, 126.9774246),
 485: (37.55677032, 126.9731979),
 3013: (37.56761551, 126.9872437),
 4761: (37.56467056, 126.9908829),
 4762: (37.56693268, 126.9825821),
 4772: (37.56253433, 126.972496),
 4774: (37.56590271, 126.981781),
 4775: (37.56599045, 126.9842758),
 4776: (37.56005478, 126.9809418),
 4778: (37.56520844, 126.9874268),
 4784: (37.56459045, 126.9907684),
 4785: (37.56689835, 126.9877396),
 4791: (37.56109619, 126.9874649),
 800: (37.53243256, 126.9547424),
 802: (37.54115295, 127.0022125),
 803: (37.53813934, 127.004097),
 805: (37.53675842, 126.9700012),
 806: (37.5330658, 126.9607315),
 807: (37.55227661, 126.9726868),
 808: (37.520504, 126.9897385),
 809: (37.53016663, 127.0074387),
 810: (37.53841019, 126.9866486),
 811: (37.53507996, 126.9853821),
 812: (37.53483963, 126.9776611),
 813: (37.53351212, 126.9722748),
 815: (37.51850891, 126.9787979),
 816: (37.53014755, 126.968483),
 817: (37.53345108, 126.9717331),
 818: (37.54489517, 126.9693832),
 819: (37.54165268, 126.9705048),
 820: (37.54902649, 126.9719467),
 822: (37.52204132, 126.9655228),
 823: (37.54232025, 126.9619598),
 825: (37.52033615, 126.9942627),
 827: (37.54188538, 126.97966),
 828: (37.54407883, 126.9720001),
 829: (37.52293015, 126.9616928),
 830: (37.53442383, 126.9485703),
 831: (37.53427887, 126.9885635),
 832: (37.5212822, 126.973465),
 834: (37.53900909, 126.96138),
 835: (37.54198074, 126.9715424),
 836: (37.53142166, 126.9514999),
 837: (37.52906036, 127.0067291),
 838: (37.5444603, 126.9723892),
 839: (37.5240097, 127.0014496),
 840: (37.52365112, 126.9702683),
 841: (37.52960968, 126.9688721),
 843: (37.53379822, 126.9886704),
 844: (37.5271492, 126.9551621),
 845: (37.53269958, 126.9643784),
 846: (37.54650116, 126.9809494),
 847: (37.53452301, 126.9775009),
 848: (37.53488922, 126.9756241),
 849: (37.53607941, 126.9734192),
 850: (37.53739929, 126.9689255),
 851: (37.54047775, 126.9581146),
 852: (37.53452682, 126.9471817),
 853: (37.52856827, 126.9656906),
 854: (37.53872681, 127.0015488),
 855: (37.52272415, 126.9727707),
 857: (37.53502274, 126.9980545),
 858: (37.53440857, 126.9868927),
 859: (37.54188538, 126.9958649),
 860: (37.52069473, 126.9709778),
 863: (37.52177048, 126.977005),
 864: (37.53514099, 127.0060043),
 865: (37.54079437, 126.9978485),
 866: (37.551548, 126.9768601),
 867: (37.51990891, 126.9892349),
 868: (37.53722, 126.965019),
 869: (37.51729584, 126.9591446),
 870: (37.51731873, 126.9582977),
 4602: (37.54498672, 126.9643021),
 4604: (37.5332222, 126.9572372),
 4605: (37.51758957, 126.9592209),
 4616: (37.53248215, 126.964119),
 4617: (37.52761078, 126.9551163),
 4618: (37.53237915, 126.9525299),
 4627: (37.53851318, 126.9635544),
 3511: (37.55125046, 127.0351028),
 3513: (37.56460953, 127.0291977),
 3514: (37.56626129, 127.0236969),
 3515: (37.54281616, 127.0420837),
 3525: (37.54608917, 127.0250702),
 3527: (37.56179047, 127.0243912),
 3530: (37.56014633, 127.0263596),
 3531: (37.55477905, 127.0248413),
 3532: (37.56068039, 127.0267792),
 3538: (37.55089188, 127.0447617),
 506: (37.54906082, 127.0577927),
 507: (37.54820251, 127.0571137),
 508: (37.54516602, 127.0575104),
 509: (37.53965378, 127.0525894),
 510: (37.54122162, 127.0438004),
 511: (37.54458237, 127.0446091),
 512: (37.5485611, 127.0450058),
 513: (37.54630661, 127.0498047),
 514: (37.54257965, 127.0633087),
 518: (37.57152557, 127.0353546),
 519: (37.56699371, 127.0299149),
 520: (37.56385803, 127.0303192),
 521: (37.56144714, 127.0349197),
 522: (37.5486412, 127.0164261),
 523: (37.54366302, 127.014061),
 524: (37.55220032, 127.0250549),
 525: (37.55805206, 127.0403519),
 526: (37.56351089, 127.0567246),
 529: (37.56137085, 127.0636597),
 530: (37.56874847, 127.0304031),
 533: (37.54814911, 127.0210877),
 534: (37.54863358, 127.0257263),
 535: (37.5539856, 127.0335922),
 536: (37.55735016, 127.029213),
 537: (37.56035614, 127.0413971),
 538: (37.56764984, 127.0511551),
 550: (37.57164001, 127.0356598),
 556: (37.54205322, 127.020401),
 557: (37.56764221, 127.0256958),
 558: (37.56460571, 127.0365219),
 559: (37.56109619, 127.0367966),
 560: (37.55120468, 127.0689316),
 561: (37.54281616, 127.0446701),
 562: (37.55924606, 127.07341),
 563: (37.5479126, 127.0627518),
 564: (37.54792786, 127.0155716),
 565: (37.54136658, 127.0177612),
 567: (37.54459, 127.0570831),
 568: (37.57110214, 127.0235596),
 569: (37.54958344, 127.0302429),
 578: (37.54828644, 127.062088),
 579: (37.56520462, 127.0418472),
 581: (37.56101227, 127.0542374),
 582: (37.54317856, 127.0490799),
 583: (37.56797028, 127.0468903),
 585: (37.53680801, 127.0554886),
 586: (37.56594086, 127.0453949),
 587: (37.54541779, 127.0526428),
 589: (37.54415894, 127.0566559),
 594: (37.55836487, 127.0569077),
 3544: (37.55453873, 127.0437775),
 3545: (37.55657959, 127.0433579),
 3547: (37.56438065, 127.0288696),
 3548: (37.54695892, 127.0476685),
 3549: (37.55514145, 127.071106),
 3550: (37.54404068, 127.023201),
 3551: (37.55979919, 127.0563278),
 3552: (37.54195786, 127.0427704),
 3553: (37.565979, 127.0431137),
 3555: (37.56681824, 127.0291519),
 3556: (37.55610657, 127.019783),
 3557: (37.55653, 127.0391312),
 3558: (37.56339645, 127.0418701),
 3559: (37.54590988, 127.0446014),
 3560: (37.56370926, 127.0564499),
 3561: (37.55926895, 127.0383987),
 3600: (37.56119156, 127.0496826),
 4353: (37.54655838, 127.0499878),
 4360: (37.54824448, 127.0595779),
 4362: (37.5540123, 127.0415497),
 3500: (37.55758667, 127.0796967),
 3501: (37.53950119, 127.0830002),
 3502: (37.56565857, 127.0842972),
 3503: (37.55048752, 127.1089554),
 3504: (37.53805161, 127.0765991),
 3505: (37.5352211, 127.0683975),
 3506: (37.53701401, 127.0610962),
 3507: (37.54595184, 127.0780029),
 3508: (37.54822159, 127.0678787),
 3509: (37.55341721, 127.0731964),
 3510: (37.56864929, 127.0862503),
 3516: (37.54370499, 127.0932465),
 3517: (37.5625267, 127.0822754),
 3518: (37.55686188, 127.0791397),
 3520: (37.54251862, 127.0840836),
 3521: (37.54342651, 127.0966187),
 3523: (37.54171753, 127.0801697),
 3524: (37.55023575, 127.073822),
 3528: (37.55059814, 127.1105118),
 3529: (37.54978943, 127.0759277),
 3533: (37.53913879, 127.0706177),
 3534: (37.54013824, 127.0692825),
 3535: (37.559158, 127.087517),
 3536: (37.53181076, 127.0807419),
 3537: (37.54848862, 127.0937576),
 3541: (37.54124832, 127.06604),
 3542: (37.54504013, 127.0899582),
 500: (37.54706955, 127.0742722),
 501: (37.53730774, 127.0703507),
 502: (37.53186035, 127.0671921),
 505: (37.53701019, 127.0822449),
 515: (37.53023529, 127.0868301),
 516: (37.54840469, 127.0693665),
 539: (37.55979538, 127.0742035),
 540: (37.55603027, 127.0786438),
 542: (37.53546524, 127.0944824),
 543: (37.53596878, 127.0946732),
 544: (37.54072952, 127.1029053),
 546: (37.53247833, 127.0850906),
 548: (37.5297699, 127.0748596),
 549: (37.55122375, 127.0897064),
 551: (37.54006195, 127.0944977),
 552: (37.53657913, 127.0929718),
 553: (37.57125473, 127.0798035),
 555: (37.53784943, 127.0921707),
 571: (37.54849625, 127.0747604),
 572: (37.5653801, 127.0865097),
 573: (37.54523087, 127.0847321),
 574: (37.55184937, 127.0889816),
 575: (37.56429291, 127.086937),
 576: (37.54483032, 127.1042633),
 577: (37.54654694, 127.1061325),
 584: (37.54782867, 127.0726318),
 588: (37.53268814, 127.0674973),
 590: (37.53989029, 127.0733643),
 591: (37.54277802, 127.0753708),
 592: (37.54191208, 127.0776367),
 593: (37.52858734, 127.0778732),
 3543: (37.55137253, 127.07444),
 3563: (37.53680038, 127.0908356),
 3564: (37.54720306, 127.0978622),
 3566: (37.53507233, 127.0761108),
 3569: (37.53956604, 127.0724411),
 3570: (37.53809738, 127.0890198),
 3571: (37.54434967, 127.0654068),
 3573: (37.5513382, 127.0767136),
 3575: (37.53657532, 127.0825806),
 3578: (37.55500793, 127.0858154),
 3579: (37.54788971, 127.0674515),
 3581: (37.54747009, 127.073967),
 3582: (37.54798889, 127.0695038),
 3586: (37.55771255, 127.0772705),
 3587: (37.54246521, 127.0942307),
 3588: (37.55237198, 127.0735397),
 600: (37.58991241, 127.0686798),
 601: (37.57594681, 127.0373612),
 602: (37.57217407, 127.0713882),
 604: (37.56965637, 127.0559616),
 605: (37.57419968, 127.0264969),
 606: (37.58462524, 127.0702896),
 607: (37.60271072, 127.0678635),
 608: (37.58131027, 127.0553436),
 609: (37.58774567, 127.037384),
 610: (37.57308578, 127.0521622),
 612: (37.57366562, 127.0308151),
 613: (37.57527161, 127.023468),
 614: (37.57768631, 127.0310135),
 615: (37.57638168, 127.0351105),
 616: (37.58256149, 127.0543671),
 617: (37.57420349, 127.0576935),
 621: (37.57471848, 127.0533905),
 622: (37.57779312, 127.0578308),
 623: (37.58369827, 127.0538559),
 624: (37.57418823, 127.0458908),
 625: (37.56819153, 127.0571747),
 626: (37.56115341, 127.0709686),
 627: (37.57863235, 127.071907),
 628: (37.58681488, 127.067543),
 630: (37.57485199, 127.0403061),
 631: (37.5681839, 127.0512772),
 633: (37.58040619, 127.0448227),
 634: (37.59601974, 127.0598297),
 635: (37.58751678, 127.0527725),
 636: (37.59090042, 127.0425873),
 637: (37.59161377, 127.0457916),
 638: (37.58300781, 127.0609741),
 639: (37.58519745, 127.0609512),
 640: (37.58245468, 127.0444946),
 641: (37.57375336, 127.0385361),
 642: (37.5701561, 127.048584),
 643: (37.56697083, 127.0744171),
 646: (37.56186676, 127.0643768),
 647: (37.60279846, 127.0672684),
 648: (37.56669998, 127.0624237),
 650: (37.59153366, 127.0677414),
 652: (37.57653046, 127.0659409),
 654: (37.57762146, 127.0521088),
 656: (37.58723831, 127.0431366),
 657: (37.57551956, 127.0487747),
 658: (37.57294846, 127.0661469),
 659: (37.57835007, 127.0333862),
 660: (37.57799911, 127.0376282),
 661: (37.59460068, 127.0519638),
 663: (37.59489059, 127.0630264),
 664: (37.58412933, 127.0579376),
 665: (37.59960556, 127.0686417),
 666: (37.60362244, 127.0708313),
 667: (37.58659363, 127.0469971),
 668: (37.56799698, 127.068779),
 669: (37.57214737, 127.0446091),
 670: (37.58968735, 127.061409),
 671: (37.57734299, 127.0233765),
 672: (37.57859039, 127.0238495),
 673: (37.58407974, 127.0310364),
 674: (37.58655167, 127.0331421),
 675: (37.5720253, 127.0770035),
 676: (37.58143234, 127.0354767),
 677: (37.5801506, 127.0457993),
 678: (37.57655716, 127.0743103),
 679: (37.57787704, 127.0616837),
 680: (37.59238434, 127.0574112),
 681: (37.5798378, 127.0563736),
 4102: (37.59383774, 127.0678177),
 4103: (37.59436417, 127.0645981),
 4104: (37.56324005, 127.057991),
 4105: (37.57738495, 127.0719833),
 4107: (37.5676918, 127.0578919),
 4108: (37.57958984, 127.0308075),
 4110: (37.59955215, 127.069809),
 4112: (37.59128571, 127.0403824),
 4113: (37.58392334, 127.0682755),
 4116: (37.59087372, 127.065361),
 4117: (37.57130051, 127.0336227),
 4121: (37.57014847, 127.0299225),
 4122: (37.57846832, 127.0668945),
 4123: (37.50543213, 126.9415131),
 1401: (37.61473846, 127.0763626),
 1402: (37.60007095, 127.1023331),
 1403: (37.59424973, 127.0765762),
 1404: (37.59529877, 127.0800324),
 1405: (37.59909821, 127.0929489),
 1406: (37.60625076, 127.1082687),
 1407: (37.61151123, 127.0778885),
 1408: (37.61072159, 127.0774765),
 1410: (37.57778168, 127.0901871),
 1411: (37.59254074, 127.0867386),
 1412: (37.59096146, 127.0870667),
 1413: (37.61756134, 127.0903091),
 1414: (37.5815773, 127.0884857),
 1416: (37.59521866, 127.0859985),
 1418: (37.61743927, 127.1090164),
 1420: (37.61394501, 127.097702),
 1421: (37.61246109, 127.1033783),
 1422: (37.62009811, 127.1064606),
 1424: (37.6063118, 127.1077423),
 1425: (37.58745956, 127.0959702),
 1426: (37.57358932, 127.0868225),
 1427: (37.57429886, 127.0869141),
 1428: (37.61602402, 127.085968),
 1429: (37.59995651, 127.0800018),
 1430: (37.60615158, 127.092598),
 1431: (37.60649872, 127.0954514),
 1433: (37.60207748, 127.0795822),
 1434: (37.57986832, 127.0823669),
 1435: (37.60868073, 127.1007919),
 1436: (37.60588074, 127.1006317),
 1437: (37.5834198, 127.0799255),
 1438: (37.61616898, 127.093483),
 1440: (37.58637238, 127.0800705),
 1441: (37.61671066, 127.110733),
 1442: (37.59859085, 127.0798187),
 1443: (37.59552002, 127.0987778),
 1444: (37.57402802, 127.0805435),
 1445: (37.5799408, 127.0793991),
 1446: (37.59130096, 127.0803299),
 1447: (37.58890152, 127.0872803),
 1448: (37.59732056, 127.089798),
 1449: (37.59655762, 127.0858383),
 1450: (37.61963654, 127.0850449),
 1451: (37.59275818, 127.07267),
 1452: (37.58565521, 127.0750504),
 1453: (37.60460281, 127.1092529),
 1454: (37.6073494, 127.0785904),
 1455: (37.59632874, 127.0858994),
 1456: (37.59511185, 127.1003265),
 1457: (37.58975983, 127.0932388),
 1458: (37.59733963, 127.0930862),
 1459: (37.58034897, 127.0926514),
 1461: (37.593853, 127.0750732),
 1462: (37.59386826, 127.0765228),
 1463: (37.57407761, 127.0850067),
 1464: (37.60305405, 127.0790024),
 1465: (37.61314774, 127.1051483),
 1466: (37.61882401, 127.0875702),
 1467: (37.61362076, 127.1011505),
 1468: (37.6114769, 127.0773926),
 1469: (37.60982132, 127.0781326),
 1470: (37.60520172, 127.0785828),
 1471: (37.61535263, 127.0784912),
 1472: (37.60408401, 127.0792313),
 1473: (37.59489059, 127.0749512),
 1474: (37.59581375, 127.08284),
 1477: (37.57598495, 127.0796051),
 1478: (37.59832764, 127.0922699),
 1479: (37.58105469, 127.0820923),
 1480: (37.58111191, 127.080101),
 1302: (37.58876419, 127.0063095),
 1303: (37.59169388, 127.012497),
 1304: (37.59440231, 126.9923096),
 1305: (37.58932877, 127.0164337),
 1306: (37.58844757, 127.0067062),
 1308: (37.58259201, 127.0289764),
 1314: (37.60243988, 127.0116882),
 1315: (37.60776138, 127.0032806),
 1316: (37.60726166, 127.0028381),
 1318: (37.60308456, 127.0247879),
 1319: (37.6030426, 127.0332718),
 1320: (37.59928513, 127.0346222),
 1321: (37.59328842, 127.0366669),
 1322: (37.59806824, 127.0392761),
 1323: (37.60043335, 127.0402069),
 1325: (37.60580826, 127.0477371),
 1326: (37.60606766, 127.0473175),
 1327: (37.60734177, 127.0506821),
 1328: (37.6026268, 127.0416336),
 1332: (37.61355591, 127.0660934),
 1333: (37.61052322, 127.0597992),
 1334: (37.61299896, 127.0613098),
 1336: (37.59125137, 127.0140076),
 1337: (37.59038162, 127.0171356),
 1338: (37.5868988, 127.020752),
 1339: (37.610569, 127.0335083),
 1340: (37.61784363, 127.0550003),
 1342: (37.59261703, 126.9979324),
 1343: (37.58924866, 127.0073776),
 1344: (37.60028839, 127.0137024),
 1346: (37.60897827, 127.0202484),
 1347: (37.60710526, 127.0214996),
 1348: (37.60475159, 127.0227585),
 1349: (37.62382889, 127.0502014),
 1351: (37.5794487, 127.0241928),
 1352: (37.58388138, 127.0170975),
 1353: (37.60083008, 127.0235519),

In [16]:
office_data['location_map'] = office_data['code'].map(locationDict)

In [17]:
office_data.head()

,month,code,office,rentals,returns,location_map
0,201806,101,101. (구)합정동 주민센터,832,807,"(37.549561, 126.905754)"
1,201806,102,102. 망원역 1번출구 앞,2819,2568,"(37.5556488, 126.9106293)"
2,201806,103,103. 망원역 2번출구 앞,1977,1769,"(37.55495071, 126.9108353)"
3,201806,104,104. 합정역 1번출구 앞,1682,1610,"(37.55062866, 126.9149857)"
4,201806,105,105. 합정역 5번출구 앞,1105,925,"(37.55000687, 126.9148254)"

In [18]:
office_data[['latitude','logitude']] = pd.DataFrame(office_data.location_map.tolist(), index= office_data.index)
office_data.head()

,month,code,office,rentals,returns,location_map,latitude,logitude
0,201806,101,101. (구)합정동 주민센터,832,807,"(37.549561, 126.905754)",37.549561,126.905754
1,201806,102,102. 망원역 1번출구 앞,2819,2568,"(37.5556488, 126.9106293)",37.555649,126.910629
2,201806,103,103. 망원역 2번출구 앞,1977,1769,"(37.55495071, 126.9108353)",37.554951,126.910835
3,201806,104,104. 합정역 1번출구 앞,1682,1610,"(37.55062866, 126.9149857)",37.550629,126.914986
4,201806,105,105. 합정역 5번출구 앞,1105,925,"(37.55000687, 126.9148254)",37.550007,126.914825

In [19]:
office_data.to_excel("Rental_Office_July_to_Nov_2018.xlsx")

In [3]:
office_data2 = pd.read_csv('../data/rental_office_(jan_to_june_2018).csv', encoding= 'unicode_escape')
office_data2.head()

      month   code                      office  rentals  returns
0  '201801'  '108'            ' ¼­±³µ¿ »ç°Å¸®'      355      422
1  '201801'  '503'      ' ´õ¼¥½ºÅ¸½ÃÆ¼ Cµ¿ ¾Õ'      287      256
2  '201801'  '731'  ' ¼­¿ï½Ã µµ·ÎÈ¯°æ°ü¸®¼¾ÅÍ'        0        4
3  '201801'  '504'       ' ½ÅÀÚÃÊ±³ÀÔ±¸±³Â÷·Î'      370      368
4  '201801'  '740'                 ' À¸¶ä°ø¿ø'        0        1

In [61]:
import numpy as np
office_data2.code.apply(lambda x: str(x)[1:-1] if not pd.isna(x) else np.nan)

0       108
1       503
2       731
3       504
4       740
       ...
7007    722
7008    723
7009    724
7010    725
7011    726
Name: code, Length: 7012, dtype: object